/**
 * 8 presets email ciblés. Chaque preset définit palette + typo + style bouton.
 * Utilisés par le builder v2 (design system) et le compiler v2 pour produire
 * du HTML inline-styled.
 */

import type { EmailPreset } from './design-types'

const FONT_SANS = "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" as const
const FONT_SERIF = "Georgia, 'Times New Roman', serif" as const
const FONT_DISPLAY = "'Playfair Display', Georgia, serif" as const
const FONT_LORA = "'Lora', Georgia, serif" as const
const FONT_DM_SANS = "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif" as const
const FONT_RALEWAY = "'Raleway', -apple-system, BlinkMacSystemFont, sans-serif" as const
const FONT_SOURCE_SERIF = "'Source Serif 4', Georgia, serif" as const

export const EMAIL_PRESETS: EmailPreset[] = [
  {
    id: 'classique',
    name: 'Classique',
    style: 'light',
    primary: '#111111',
    background: '#f4f4f5',
    containerBg: '#ffffff',
    footerBg: '#fafafa',
    textColor: '#18181b',
    mutedColor: '#71717a',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'rounded',
    buttonShadow: false,
  },
  {
    id: 'editorial',
    name: 'Editorial',
    style: 'light',
    primary: '#111111',
    background: '#faf8f3',
    containerBg: '#ffffff',
    footerBg: '#f4f1ea',
    textColor: '#1c1917',
    mutedColor: '#78716c',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_DISPLAY,
    buttonShape: 'sharp',
    buttonShadow: false,
  },
  {
    id: 'impact',
    name: 'Impact',
    style: 'dark',
    primary: '#EF4444',
    background: '#0f0f0f',
    containerBg: '#1a1a1a',
    footerBg: '#000000',
    textColor: '#f4f4f5',
    mutedColor: '#a1a1aa',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'rounded',
    buttonShadow: true,
  },
  {
    id: 'ocean',
    name: 'Ocean',
    style: 'light',
    primary: '#3B82F6',
    background: '#e0f2fe',
    containerBg: '#ffffff',
    footerBg: '#e0f2fe',
    textColor: '#0c4a6e',
    mutedColor: '#0369a1',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'rounded',
    buttonShadow: false,
  },
  {
    id: 'foret',
    name: 'Forêt',
    style: 'light',
    primary: '#10B981',
    background: '#ecfdf5',
    containerBg: '#ffffff',
    footerBg: '#ecfdf5',
    textColor: '#1f2937',
    mutedColor: '#6b7280',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SERIF,
    buttonShape: 'pill',
    buttonShadow: false,
  },
  {
    id: 'violet',
    name: 'Violet',
    style: 'dark',
    primary: '#A855F7',
    background: '#1a0b2e',
    containerBg: '#0f0817',
    footerBg: '#000000',
    textColor: '#f4f4f5',
    mutedColor: '#a1a1aa',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_DISPLAY,
    buttonShape: 'rounded',
    buttonShadow: true,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    style: 'light',
    primary: '#171717',
    background: '#fafafa',
    containerBg: '#ffffff',
    footerBg: '#fafafa',
    textColor: '#18181b',
    mutedColor: '#a1a1aa',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'sharp',
    buttonShadow: false,
  },
  {
    id: 'midnight',
    name: 'Midnight',
    style: 'dark',
    primary: '#22D3EE',
    background: '#020617',
    containerBg: '#0f172a',
    footerBg: '#000000',
    textColor: '#f4f4f5',
    mutedColor: '#a1a1aa',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'rounded',
    buttonShadow: true,
  },
  {
    id: 'sunshine',
    name: 'Sunshine',
    style: 'light',
    primary: '#EAB308',
    background: '#fefce8',
    containerBg: '#ffffff',
    footerBg: '#fef3c7',
    textColor: '#1f2937',
    mutedColor: '#78716c',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'pill',
    buttonShadow: false,
  },
  {
    id: 'luxe',
    name: 'Luxe',
    style: 'dark',
    primary: '#D4AF37',
    background: '#0a0a0a',
    containerBg: '#141414',
    footerBg: '#000000',
    textColor: '#f4f4f5',
    mutedColor: '#a1a1aa',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_DISPLAY,
    buttonShape: 'sharp',
    buttonShadow: true,
  },
  {
    id: 'energie',
    name: 'Énergie',
    style: 'light',
    primary: '#F97316',
    background: '#fff7ed',
    containerBg: '#ffffff',
    footerBg: '#fff7ed',
    textColor: '#1c1917',
    mutedColor: '#78716c',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'rounded',
    buttonShadow: true,
  },
  {
    id: 'rosegold',
    name: 'Rose Gold',
    style: 'light',
    primary: '#EC4899',
    background: '#ffe4e6',
    containerBg: '#fffbfe',
    footerBg: '#ffe4e6',
    textColor: '#1f2937',
    mutedColor: '#6b7280',
    fontFamily: FONT_DM_SANS,
    headingFontFamily: FONT_DM_SANS,
    buttonShape: 'pill',
    buttonShadow: false,
  },
  {
    id: 'zen',
    name: 'Zen',
    style: 'light',
    primary: '#06B6D4',
    background: '#f0fdfa',
    containerBg: '#ffffff',
    footerBg: '#f0fdfa',
    textColor: '#134e4a',
    mutedColor: '#5eead4',
    fontFamily: FONT_LORA,
    headingFontFamily: FONT_LORA,
    buttonShape: 'rounded',
    buttonShadow: false,
  },
  {
    id: 'bootcamp',
    name: 'Bootcamp',
    style: 'dark',
    primary: '#84CC16',
    background: '#0a0a0a',
    containerBg: '#171717',
    footerBg: '#000000',
    textColor: '#f4f4f5',
    mutedColor: '#a1a1aa',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'rounded',
    buttonShadow: true,
  },
  {
    id: 'prestige',
    name: 'Prestige',
    style: 'dark',
    primary: '#1E40AF',
    background: '#0c1222',
    containerBg: '#0a0f1f',
    footerBg: '#000814',
    textColor: '#f4f4f5',
    mutedColor: '#94a3b8',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SOURCE_SERIF,
    buttonShape: 'rounded',
    buttonShadow: false,
  },
  {
    id: 'naturel',
    name: 'Naturel',
    style: 'light',
    primary: '#65A30D',
    background: '#fef7e6',
    containerBg: '#fffcf5',
    footerBg: '#fef7e6',
    textColor: '#1f2937',
    mutedColor: '#6b7280',
    fontFamily: FONT_LORA,
    headingFontFamily: FONT_LORA,
    buttonShape: 'pill',
    buttonShadow: false,
  },
  {
    id: 'sunset',
    name: 'Sunset',
    style: 'light',
    primary: '#FB7185',
    background: '#fff1f2',
    containerBg: '#ffffff',
    footerBg: '#fff1f2',
    textColor: '#1f2937',
    mutedColor: '#6b7280',
    fontFamily: FONT_RALEWAY,
    headingFontFamily: FONT_RALEWAY,
    buttonShape: 'rounded',
    buttonShadow: true,
  },
  {
    id: 'bordeaux',
    name: 'Bordeaux',
    style: 'light',
    primary: '#9F1239',
    background: '#fef2f2',
    containerBg: '#ffffff',
    footerBg: '#fef2f2',
    textColor: '#1f2937',
    mutedColor: '#6b7280',
    fontFamily: FONT_SERIF,
    headingFontFamily: FONT_DISPLAY,
    buttonShape: 'sharp',
    buttonShadow: false,
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    style: 'light',
    primary: '#C2410C',
    background: '#fef3c7',
    containerBg: '#fffbeb',
    footerBg: '#fef3c7',
    textColor: '#1c1917',
    mutedColor: '#78716c',
    fontFamily: FONT_SOURCE_SERIF,
    headingFontFamily: FONT_SOURCE_SERIF,
    buttonShape: 'rounded',
    buttonShadow: false,
  },
  {
    id: 'anthracite',
    name: 'Anthracite',
    style: 'dark',
    primary: '#94A3B8',
    background: '#1e293b',
    containerBg: '#0f172a',
    footerBg: '#020617',
    textColor: '#f1f5f9',
    mutedColor: '#94a3b8',
    fontFamily: FONT_SANS,
    headingFontFamily: FONT_SANS,
    buttonShape: 'rounded',
    buttonShadow: false,
  },
  {
    id: 'tropical',
    name: 'Tropical',
    style: 'light',
    primary: '#14B8A6',
    background: '#f0fdfa',
    containerBg: '#ffffff',
    footerBg: '#f0fdfa',
    textColor: '#134e4a',
    mutedColor: '#5eead4',
    fontFamily: FONT_DM_SANS,
    headingFontFamily: FONT_DM_SANS,
    buttonShape: 'pill',
    buttonShadow: false,
  },
  {
    id: 'lavande',
    name: 'Lavande',
    style: 'light',
    primary: '#8B5CF6',
    background: '#faf5ff',
    containerBg: '#ffffff',
    footerBg: '#faf5ff',
    textColor: '#1f1b2e',
    mutedColor: '#6b7280',
    fontFamily: FONT_RALEWAY,
    headingFontFamily: FONT_DISPLAY,
    buttonShape: 'rounded',
    buttonShadow: true,
  },
]

export const DEFAULT_EMAIL_PRESET_ID = 'classique' as const

export function getEmailPresetByIdOrDefault(id: string | null | undefined): EmailPreset {
  return EMAIL_PRESETS.find((p) => p.id === id) || EMAIL_PRESETS[0]
}

export const FEATURED_EMAIL_PRESET_IDS = ['classique', 'impact', 'ocean', 'foret'] as const
